export const SET_LOADING: string = 'SET_LOADING'
export const GET_ALL_POSTS: string = 'GET_ALL_POSTS'
export const GET_ALL_POSTS_SUCCESS: string = 'GET_ALL_POSTS_SUCCESS'
export const GET_POST_BY_ID: string = 'GET_POST_BY_ID'
export const CREATE_POST: string = 'CREATE_POST'
